name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
    IMAGE_NAME: u8g2_font_builder
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag  ${{env.IMAGE_NAME}}:$(date +%s) --tag ${{env.IMAGE_NAME}}:latest
    - name: Login to Tencentyun Docker 
      uses: docker/login-action@v1.14.1
      with:
        registry: ccr.ccs.tencentyun.com
        username: 38414842
        password: ${{ secrets.DOCKER_PWD }}
    - name: Push to Tencentyun Docker Hub 
      run: docker push ${{env.IMAGE_NAME}}:[latest]


    
